# Config port
server:
  port: 8080
# Config mysql
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
app:
  page:
    blog:
      size: 9
    room:
      size: 5

  file:
    location: C:/Users/ADMIN/Desktop/java-booking/resources/static/uploads
    rooms:  ${app.file.location}/rooms
    url-prefix: http://localhost:${server.port}/file
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456789n
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
      format_sql: false
      SQL: debug
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mail:
    host: smtp.mailtrap.io
    username: e92267207a1fe8
    password: da538f8b843909
    port: 2525
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        from: dev@gobysend.com
        debug: false

  thymeleaf:
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:static
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org.springframework:
      autoconfigure: ERROR
    hibernate: ERROR
    security: ERROR
    web: DEBUG
    com: DEBUG

#Send mail
mail:
  sender-name: ATOLI RESORT
  sender-email:
  password: